### ISSUE TITLE
helm-hunks depends on git-gutter+

### ISSUE THREAD

**Issue by dholm** [torgeir/helm-hunks.el#1]
Hi,
It appears helm-hunks depends on git-gutter+ but it isn't listed in the "Package-Requires".

I got the following error when I tried to load it:

```
Debugger entered--Lisp error: (void-variable git-gutter+-mode)
```

**Comment by torgeir** [comment]
Ouch, that's not intentional. I'll add a `boundp` to it!

**Comment by dholm** [comment]
Awesome, thanks!

So git-gutter+ is an optional dependency?  I've added a helm-hunks recipe to `el-get` and I'm just wondering whether to add `git-gutter+` as a required dependency. :)

**Comment by torgeir** [comment]
> So git-gutter+ is an optional dependency?

That was my intention, yes.

https://github.com/torgeir/helm-hunks.el/blob/3cf2705336f8c0f376f17cd698b5d05e53cffe10/helm-hunks.el#L79

**Comment by dholm** [comment]
You need to add an apostrophe in front of `git-gutter+` in the `boundp` expression.

**Comment by torgeir** [comment]
Oh my god, need more ☕ 

Try now!

**Comment by dholm** [comment]
Hehe, I know how it feels.  Anyway, it's working perfectly now, thanks!

**Comment by torgeir** [comment]
Alright, thanks yourself for reporting it!
