### ISSUE TITLE
Does not work when git.exe prints warnings a la "The file will have its original line endings in your working directory"

### ISSUE THREAD

**Issue by vjohansen** [torgeir/helm-hunks.el#10]
helm-hunks shows a bunch of "The file will have its original line endings.."

When I run "git --no-pager diff --no-color --no-ext-diff --unified=0" in the repo I see 

    warning: LF will be replaced by CRLF in vj-react-app/package-lock.json.
    The file will have its original line endings in your working directory
    warning: LF will be replaced by CRLF in vj-react-app/package.json.
    The file will have its original line endings in your working directory
    diff --git a/vj-react-app/package-lock.json b/vj-react-app/package-lock.json
    index b9406c0..61dbca0 100644
    --- a/vj-react-app/package-lock.json
    +++ b/vj-react-app/package-lock.json

I tried to remove warnings output in helm-hunks--get-diffs by filtering split-diff-lines-without-empties but it seems more is needed.

**Comment by torgeir** [comment]
Hey! Thanks. Did you consider configuring git to respect or handle/fix the underlying issues that are being warned about? Here are a good couple of suggestions:

https://stackoverflow.com/a/5834094

I’m a bit hesitant to have helm-hunks needing to handle those lines as they are not recognizable without hardcoding the messages, which e.g. might change for new versions git

**Comment by vjohansen** [comment]
I have fixed the underlying issue.

I was thinking it would be a good idea to skip lines until the first line beginning with "diff"
