### ISSUE TITLE
Limit to current buffer

### ISSUE THREAD

**Issue by csantosb** [torgeir/helm-hunks.el#3]
Hi, thanks for this package; I am investigating if it is possible to limit the hunks to current buffer only, by customizing one of the git commands with a let macro, any ideas ?

**Comment by torgeir** [comment]
Hi!

I think that is doable, either by changing around some of the git commands, or by filtering the hunks by file-name after some place after the call to `helm-hunks--get-hunks-by-file`. Its resulting list contains cons pairs of each file-name and their corresponding hunks.

Feel free to have a go! :)

**Comment by csantosb** [comment]
Yeah, I tried to do something like

```
(let ((helm-hunks--cmd-file-names
   (format "git --no-pager diff --name-only | grep %s"
       (file-name-nondirectory (buffer-file-name (current-buffer))))))
  (helm-hunks))
```

to limit the diff command to the current buffer file name, but doesn't
work, any idea why ?

**Comment by torgeir** [comment]
Not really, no.. Something along those lines ought to work.

**Comment by csantosb** [comment]
As a second attempt I get

```
(let* ((current-file
         (file-relative-name
      (buffer-file-name (current-buffer))(helm-hunks--get-git-root)))
         (helm-hunks--cmd-diffs
          (format "git --no-pager diff --no-color --no-ext-diff --unified=0 %s" current-file))
         (helm-hunks--cmd-file-names
          (format "git --no-pager diff --name-only %s" current-file)))
    (helm-hunks))
```

which doesn't work neither. There must be something else around.

**Comment by torgeir** [comment]
You were close, though..`git diff` needs the path not relative to the root project git folder (or you would have to `cd` to the root folder like `helm-hunks--stage-hunk`does), but rather with the file name relative to the current folder (i.e. without the `(helm-hunks--get-git-root)`). `git diff` also enjoys a `--` to distinguish refs from clashing file names.

I added this functionality with `helm-hunks-current-buffer` in 566ed2603f614390972bc46cdc14582b97275ee6

**Comment by torgeir** [comment]
Actually, such an approach made [implementing unstaging/resetting of staged hunks a breeze](https://github.com/torgeir/helm-hunks.el/blob/90efb7305a7cb7b5007c792d28b9572681bdb4d4/helm-hunks.el#L385-L408). You'll find it in 1.4

**Comment by csantosb** [comment]
Great ! This package is really useful, thanks for this.
