### ISSUE TITLE
keys missing

### ISSUE THREAD

**Issue by csantosb** [torgeir/helm-hunks.el#8]
I just realized that the bindings are gone: no preview, no staging, nothing. I just get an "key in undefined" message. Is this just me or there is something wrong here ?

I am using helm-core 2.5.2 and emacs 25.1.1. Any ideas ?

**Comment by torgeir** [comment]
Waat. You're right! They've been there before, I don't know what's going on, have to look into it

**Comment by torgeir** [comment]
I won't have time to look into this in the nearest future, but PRs are welcome!

**Comment by torgeir** [comment]
Seems to be an issue with some late versions of helm, where the source itself also needs the `:keymap` defined.

Workaround in https://github.com/torgeir/helm-hunks.el/commit/b50cfc4b9bfd5ae9a530e5e118002f37f7e12786

**Comment by csantosb** [comment]
Tested and seems ok to me. 

Thanks a lot !
