### ISSUE TITLE
Open `helm-hunks` with the diffs shown

### ISSUE THREAD

**Issue by wagk** [torgeir/helm-hunks.el#9]
Currently when `helm-hunks` is opened, the changes are all folded, and require a separate chord to unfold

Is there a flag of some sort to unfold the diffs automatically?

**Comment by csantosb** [comment]
I guess by now you may set

    (setq helm-hunks--is-preview t)

but this is just a temporary solution, as this variable is not supposed to be set by users.

**Comment by torgeir** [comment]
Oh, I completely missed this, sorry about that.

> as this variable is not supposed to be set by users

Yeah, but I like the idea of this as a config option. We could just expose it. I recon if you'd toggle it back off from inside helm-hunks, you'd want it off the next time you open it as well - which is the effect that this would give.

**Comment by csantosb** [comment]
Exposing it to users should be enough. The current behaviour if fine for me.

**Comment by torgeir** [comment]
Fixed, https://github.com/torgeir/helm-hunks.el/commit/287685254002d47432f267884ac6a83de67ea07c adds 

```elisp
(setq helm-hunks-preview-diffs t)
```
